# Mobile Price Prediction using machine learning

In this project, we will predict the price of mobile phones given with <br>
various features in the dataset. This dataset is taken from Kaggle: https://www.kaggle.com/code/ibraheemseyam/mobile-price-classification-99/data <br>
the train and test splits of the data are provided on kaggle. You can download and apply ML algorithms for prediction purpose. In this project, we will explore various supervised ML algorithm to see their efficacy on this dataset. <br>
Before applying Machine learning, we will explore a bit about dataset and apply necessary feature engineering if required.

In [1]:
#import the libararies
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [5]:
#impor the training data
train_data =pd.read_csv('train.csv')
train_data.head()

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  \
0            842     0          2.2         0   1       0           7    0.6   
1           1021     1          0.5         1   0       1          53    0.7   
2            563     1          0.5         1   2       1          41    0.9   
3            615     1          2.5         0   0       0          10    0.8   
4           1821     1          1.2         0  13       1          44    0.6   

   mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  talk_time  \
0        188        2  ...         20       756  2549     9     7         19   
1        136        3  ...        905      1988  2631    17     3          7   
2        145        5  ...       1263      1716  2603    11     2          9   
3        131        6  ...       1216      1786  2769    16     8         11   
4        141        2  ...       1208      1212  1411     8     2         15   

   three_g  touch_screen  wifi  price_range  
0        0             0     1            1  
1        1             1     0            2  
2        1             1     0            2  
3        1             0     0            2  
4        1             1     0            1  

[5 rows x 21 columns]

In [6]:
train_data.shape

(2000, 21)

In [8]:
"""ok ! so the dataset has 2000 rows (samples) and 21 columns (feature) including a traget variabel
 'price range.......Let us further explore the dataset'"""

"ok ! so the dataset has 2000 rows (samples) and 21 columns (feature) including a traget variabel\n 'price range.......Let us further explore the dataset'"

In [9]:
#let us check the type of variable (datatype)
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   battery_power  2000 non-null   int64  
 1   blue           2000 non-null   int64  
 2   clock_speed    2000 non-null   float64
 3   dual_sim       2000 non-null   int64  
 4   fc             2000 non-null   int64  
 5   four_g         2000 non-null   int64  
 6   int_memory     2000 non-null   int64  
 7   m_dep          2000 non-null   float64
 8   mobile_wt      2000 non-null   int64  
 9   n_cores        2000 non-null   int64  
 10  pc             2000 non-null   int64  
 11  px_height      2000 non-null   int64  
 12  px_width       2000 non-null   int64  
 13  ram            2000 non-null   int64  
 14  sc_h           2000 non-null   int64  
 15  sc_w           2000 non-null   int64  
 16  talk_time      2000 non-null   int64  
 17  three_g        2000 non-null   int64  
 18  touch_sc

In [10]:
train_data.describe()

battery_power       blue  clock_speed     dual_sim           fc  \
count    2000.000000  2000.0000  2000.000000  2000.000000  2000.000000   
mean     1238.518500     0.4950     1.522250     0.509500     4.309500   
std       439.418206     0.5001     0.816004     0.500035     4.341444   
min       501.000000     0.0000     0.500000     0.000000     0.000000   
25%       851.750000     0.0000     0.700000     0.000000     1.000000   
50%      1226.000000     0.0000     1.500000     1.000000     3.000000   
75%      1615.250000     1.0000     2.200000     1.000000     7.000000   
max      1998.000000     1.0000     3.000000     1.000000    19.000000   

            four_g   int_memory        m_dep    mobile_wt      n_cores  ...  \
count  2000.000000  2000.000000  2000.000000  2000.000000  2000.000000  ...   
mean      0.521500    32.046500     0.501750   140.249000     4.520500  ...   
std       0.499662    18.145715     0.288416    35.399655     2.287837  ...   
min       0.000000     2.000000     0.100000    80.000000     1.000000  ...   
25%       0.000000    16.000000     0.200000   109.000000     3.000000  ...   
50%       1.000000    32.000000     0.500000   141.000000     4.000000  ...   
75%       1.000000    48.000000     0.800000   170.000000     7.000000  ...   
max       1.000000    64.000000     1.000000   200.000000     8.000000  ...   

         px_height     px_width          ram         sc_h         sc_w  \
count  2000.000000  2000.000000  2000.000000  2000.000000  2000.000000   
mean    645.108000  1251.515500  2124.213000    12.306500     5.767000   
std     443.780811   432.199447  1084.732044     4.213245     4.356398   
min       0.000000   500.000000   256.000000     5.000000     0.000000   
25%     282.750000   874.750000  1207.500000     9.000000     2.000000   
50%     564.000000  1247.000000  2146.500000    12.000000     5.000000   
75%     947.250000  1633.000000  3064.500000    16.000000     9.000000   
max    1960.000000  1998.000000  3998.000000    19.000000    18.000000   

         talk_time      three_g  touch_screen         wifi  price_range  
count  2000.000000  2000.000000   2000.000000  2000.000000  2000.000000  
mean     11.011000     0.761500      0.503000     0.507000     1.500000  
std       5.463955     0.426273      0.500116     0.500076     1.118314  
min       2.000000     0.000000      0.000000     0.000000     0.000000  
25%       6.000000     1.000000      0.000000     0.000000     0.750000  
50%      11.000000     1.000000      1.000000     1.000000     1.500000  
75%      16.000000     1.000000      1.000000     1.000000     2.250000  
max      20.000000     1.000000      1.000000     1.000000     3.000000  

[8 rows x 21 columns]

In [11]:
#check null values

train_data.isnull().sum()

battery_power    0
blue             0
clock_speed      0
dual_sim         0
fc               0
four_g           0
int_memory       0
m_dep            0
mobile_wt        0
n_cores          0
pc               0
px_height        0
px_width         0
ram              0
sc_h             0
sc_w             0
talk_time        0
three_g          0
touch_screen     0
wifi             0
price_range      0
dtype: int64

In [12]:
#perfect there is no null value in the data

In [86]:
#separate the target variable from the data

y = train_data['price_range']

In [87]:
y.unique()  

array([1, 2, 3, 0], dtype=int64)

In [21]:
#ok so we have 4 class variable.. so this is multiclass problem

In [88]:
X = train_data.iloc[:, :-1]

In [89]:
X.head()

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  \
0            842     0          2.2         0   1       0           7    0.6   
1           1021     1          0.5         1   0       1          53    0.7   
2            563     1          0.5         1   2       1          41    0.9   
3            615     1          2.5         0   0       0          10    0.8   
4           1821     1          1.2         0  13       1          44    0.6   

   mobile_wt  n_cores  pc  px_height  px_width   ram  sc_h  sc_w  talk_time  \
0        188        2   2         20       756  2549     9     7         19   
1        136        3   6        905      1988  2631    17     3          7   
2        145        5   6       1263      1716  2603    11     2          9   
3        131        6   9       1216      1786  2769    16     8         11   
4        141        2  14       1208      1212  1411     8     2         15   

   three_g  touch_screen  wifi  
0        0             0     1  
1        1             1     0  
2        1             1     0  
3        1             0     0  
4        1             1     0

In [91]:
#check how many mobiles are wifi-enabled
X['wifi'].sum()

1014

In [35]:
#so out of 2000, 1014 mobile wifie

In [92]:
generation = X[['four_g','three_g']].sum()
generation

four_g     1043
three_g    1523
dtype: int64

In [70]:
#ok so we have 1043 mobilew with four_g and 1523 with 3g

In [71]:
#similarly a lot of information can be extracted! but we will now move onto 
#feature scaling becuase many features are of high range and many low. let us 
#make them in between 0 and 1.

let us split our data into train and test split

In [94]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [93]:
#we keep 80% data for training and 20% for test using Pareto principle

In [95]:
#normalize data
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler(feature_range=(0,1))

In [97]:
train_normalized= scaler.fit_transform(X_train)

In [98]:
#normalize the test data as well but in the same parameters as the train data
test_normalized = scaler.transform(X_test)  

# Model Building

In [101]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from sklearn import neighbors
from xgboost import XGBClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree
from sklearn.metrics import roc_auc_score
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import auc,roc_auc_score,roc_curve,precision_score,recall_score,f1_score
from sklearn.model_selection import train_test_split
import time as timer

# Logistic Regression

In [102]:
start = timer.time()
logit_model = LogisticRegression(max_iter=300, random_state=124)
logit_model.fit(train_normalized, y_train)
end = timer.time()
print("Finished training within {:.2f} seconds".format(end-start))

Finished training within 0.16 seconds


In [103]:
start = timer.time()
y_logit = logit_model.predict(test_normalized)
y_logit_prob = logit_model.predict_proba(test_normalized)
end = timer.time()
print("Finished training within {:.2f} seconds".format(end-start))

Finished training within 0.00 seconds


In [105]:
print("Classification report for LR: \n{}".format(classification_report(y_test,y_logit)))
print("Confusion matrix for LR: \n{}".format(confusion_matrix(y_test,y_logit)))
print("Accuracy score for LR: {:.4f}".format(accuracy_score(y_test,y_logit)))
# calculate precision, recall, and f1 scores
prec_logit = precision_score(y_test,y_logit, average='weighted')
rec_logit = recall_score(y_test,y_logit,average='weighted')
f1_logit = f1_score(y_test,y_logit,average='weighted')
print("Precision score for LR: {:.4f}".format(prec_logit))
print("Recall score for LR: {:.4f}".format(rec_logit))
print("F1 score for LR: {:.4f}".format(f1_logit))

Classification report for LR: 
              precision    recall  f1-score   support

           0       0.99      1.00      1.00       105
           1       0.91      0.95      0.92        91
           2       0.91      0.84      0.87        92
           3       0.95      0.96      0.96       112

    accuracy                           0.94       400
   macro avg       0.94      0.94      0.94       400
weighted avg       0.94      0.94      0.94       400

Confusion matrix for LR: 
[[105   0   0   0]
 [  1  86   4   0]
 [  0   9  77   6]
 [  0   0   4 108]]
Accuracy score for LR: 0.9400
Precision score for LR: 0.9396
Recall score for LR: 0.9400
F1 score for LR: 0.9394


In [106]:
#Excellent... we achieve 94% accuracy with LR

# Guassian Naive Bayes

In [107]:
start = timer.time()
gnb_model = GaussianNB()
gnb_model.fit(train_normalized, y_train)
end = timer.time()
print("Finished training within {:.2f} seconds".format(end-start))

Finished training within 0.00 seconds


In [108]:
# Predicting the test set results
y_gnb = gnb_model.predict(test_normalized)
y_gnb_prob = gnb_model.predict_proba(test_normalized)

In [109]:
print("Classification report for GNB: \n{}".format(classification_report(y_test,y_gnb)))
print("Confusion matrix for GNB: \n{}".format(confusion_matrix(y_test,y_gnb)))
print("Accuracy score for GNB: {:.2f}".format(accuracy_score(y_test,y_gnb)))
# calculate precision, recall, and f1 scores
prec_gnb = precision_score(y_test,y_gnb,average='weighted')
rec_gnb = recall_score(y_test,y_gnb,average='weighted')
f1_gnb = f1_score(y_test,y_gnb,average='weighted')
print("Precision score for GNB: {:.2f}".format(prec_gnb))
print("Recall score for GNB: {:.2f}".format(rec_gnb))
print("F1 score for GNB: {:.2f}".format(f1_gnb))

Classification report for GNB: 
              precision    recall  f1-score   support

           0       0.90      0.90      0.90       105
           1       0.77      0.68      0.72        91
           2       0.64      0.77      0.70        92
           3       0.88      0.81      0.85       112

    accuracy                           0.80       400
   macro avg       0.80      0.79      0.79       400
weighted avg       0.81      0.80      0.80       400

Confusion matrix for GNB: 
[[95 10  0  0]
 [10 62 19  0]
 [ 0  9 71 12]
 [ 0  0 21 91]]
Accuracy score for GNB: 0.80
Precision score for GNB: 0.81
Recall score for GNB: 0.80
F1 score for GNB: 0.80


# Random Forest Classifier

In [111]:
start = timer.time()
Rf_clf=RandomForestClassifier(n_estimators = 100, criterion = 'gini', random_state = 10)
Rf_clf.fit(train_normalized, y_train)
end = timer.time()
print("Finished training within {:.2f} seconds".format(end-start))

Finished training within 0.31 seconds


In [112]:
start = timer.time()
y_RF = Rf_clf.predict(test_normalized)
y_RF_prob = Rf_clf.predict_proba(test_normalized)
end = timer.time()
print("Finished testing within {:.2f} seconds".format(end-start))

Finished testing within 0.05 seconds


In [113]:
print("Classification report for RF: \n{}".format(classification_report(y_test,y_RF)))
print("Confusion matrix for RF: \n{}".format(confusion_matrix(y_test,y_RF)))
print("Accuracy score for RF: {:.4f}".format(accuracy_score(y_test,y_RF)))
# calculate precision, recall, and f1 scores
prec_rf = precision_score(y_test,y_RF,average='weighted')
rec_rf = recall_score(y_test,y_RF,average='weighted')
f1_rf = f1_score(y_test,y_RF,average='weighted')
print("Precision score for RF: {:.4f}".format(prec_rf))
print("Recall score for RF: {:.4f}".format(rec_rf))
print("F1 score for RF: {:.4f}".format(f1_rf))

Classification report for RF: 
              precision    recall  f1-score   support

           0       0.94      0.95      0.95       105
           1       0.87      0.85      0.86        91
           2       0.77      0.82      0.79        92
           3       0.91      0.88      0.89       112

    accuracy                           0.88       400
   macro avg       0.87      0.87      0.87       400
weighted avg       0.88      0.88      0.88       400

Confusion matrix for RF: 
[[100   5   0   0]
 [  6  77   8   0]
 [  0   7  75  10]
 [  0   0  14  98]]
Accuracy score for RF: 0.8750
Precision score for RF: 0.8764
Recall score for RF: 0.8750
F1 score for RF: 0.8754


# Decision Tree Classifier

In [114]:
start = timer.time()
DT_clf= DecisionTreeClassifier(max_depth=10, criterion='gini', random_state=10)
DT_clf.fit(train_normalized,y_train)
end = timer.time()
print("Finished training within {:.2f} seconds".format(end-start))

Finished training within 0.02 seconds


In [115]:
start = timer.time()
y_DT = DT_clf.predict(test_normalized)
y_DT_prob = DT_clf.predict_proba(test_normalized)
end = timer.time()
print("Finished training within {:.2f} seconds".format(end-start))

Finished training within 0.00 seconds


In [116]:
print("Classification report for DT: \n{}".format(classification_report(y_test,y_DT)))
print("Confusion matrix for DT: \n{}".format(confusion_matrix(y_test,y_DT)))
print("Accuracy score for DT: {:.4f}".format(accuracy_score(y_test,y_DT)))

# calculate precision, recall, and f1 scores
prec_dt = precision_score(y_test,y_DT, average='weighted')
rec_dt = recall_score(y_test,y_DT, average='weighted')
f1_dt = f1_score(y_test,y_DT, average='weighted')
print("Precision score for DT: {:.4f}".format(prec_dt))
print("Recall score for DT: {:.4f}".format(rec_dt))
print("F1 score for RF: {:.4f}".format(f1_dt))

Classification report for DT: 
              precision    recall  f1-score   support

           0       0.94      0.89      0.91       105
           1       0.77      0.84      0.80        91
           2       0.76      0.73      0.74        92
           3       0.88      0.89      0.88       112

    accuracy                           0.84       400
   macro avg       0.84      0.84      0.84       400
weighted avg       0.84      0.84      0.84       400

Confusion matrix for DT: 
[[ 93  12   0   0]
 [  6  76   9   0]
 [  0  11  67  14]
 [  0   0  12 100]]
Accuracy score for DT: 0.8400
Precision score for DT: 0.8420
Recall score for DT: 0.8400
F1 score for RF: 0.8403


It is amazing to see that we achieve the best results with logistic regression. <br>
Generally Tree based classifiers are better than LR. But it also depends upon dataset.<br>
Tree based leraners are best for complex dataset. 